; ------------------------------------------------------------------------------------------------------------- ;
; C64 SID (Sound Interface Device) Registers  $D400-$D41C
; ------------------------------------------------------------------------------------------------------------- ;
FRELO1              = $D400
FREHI1              = $D401
PWLO1               = $D402
PWHI1               = $D403
VCREG1              = $D404
ATDCY1              = $D405
SUREL1              = $D406
FRELO2              = $D407
FREHI2              = $D408
PWLO2               = $D409
PWHI2               = $D40A
VCREG2              = $D40B
ATDCY2              = $D40C
SUREL2              = $D40D
FRELO3              = $D40E
FREHI3              = $D40F
PWLO3               = $D410
PWHI3               = $D411
VCREG3              = $D412
ATDCY3              = $D413
SUREL3              = $D414
CUTLO               = $D415
CUTHI               = $D416
RESON               = $D417
SIGVOL              = $D418
POTX                = $D419
POTY                = $D41A
RANDOM              = $D41B
ENV3                = $D41C
